apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dask-scheduler
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dask-scheduler
  strategy:
{{ if eq .Values.rollingUpdate true }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "0%"
{{ else }}
    type: Recreate
{{- end }}
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: dask-scheduler
    spec:
      containers:
        - args:
            - dask-scheduler
            - --port
            - "8786"
            - --interface
            - eth0
            - --no-show
            - --dashboard-address
            - "8787"
          command:
            - /entrypoints/rapids-entrypoint.sh
          env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphistry}}:{{.Values.daskscheduler.repository}}-{{.Values.tag}}-{{.Values.cuda.version}}
          imagePullPolicy: {{.Values.imagePullPolicy }}           
          livenessProbe:
            exec:
              command:
                - curl
                - -Lf
                - http://localhost:8787/health
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          name: dask-scheduler
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources: {}
          volumeMounts:
            - mountPath: /opt/graphistry/data
              name: data-mount
            - mountPath: /dask-shared
              name: data-mount
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: data-mount            
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }} 
{{ if eq .Values.multiNode false }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }} 
status: {}

---
#service
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dask-scheduler
  name: dask-scheduler
spec:
  ports:
    - name: "8786"
      port: 8786
      targetPort: 8786
    - name: "8787"
      port: 8787
      targetPort: 8787
  selector:
    io.kompose.service: dask-scheduler
status:
  loadBalancer: {}


