apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dask-cuda-worker
  name: dask-cuda-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dask-cuda-worker
  strategy:
{{ if eq .Values.rollingUpdate true }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "0%"
{{ else }}
    type: Recreate
{{- end }}
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: dask-cuda-worker
    spec:
      containers:
        - args:
            - dask-cuda-worker
            - --interface
            - eth0
            - --dashboard-address localhost:8787
            - --resources GPU=10
            - dask-scheduler:8786
          command:
            - /entrypoints/rapids-entrypoint.sh
          env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphistry}}:{{.Values.daskcudaworker.repository}}-{{.Values.tag}}-{{.Values.cuda.version}}
          imagePullPolicy: {{.Values.imagePullPolicy }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -Lf http://localhost:8787/health && curl -f http://forge-etl-python:8080/workerhealth"

            failureThreshold: 1
            initialDelaySeconds: 180
            periodSeconds: 120
            timeoutSeconds: 30
          name: dask-cuda-worker
          ports:
            - containerPort: 8080
            - containerPort: 8787
          resources: {}
          volumeMounts:
            - mountPath: /opt/graphistry/data
              name: data-mount
            - mountPath: /dask-shared
              name: data-mount
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: data-mount
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}  
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
status: {}
---
#service
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dask-cuda-worker
  name: dask-cuda-worker
spec:
  ports:
    - name: "8786"
      port: 8786
      targetPort: 8786
    - name: "8787"
      port: 8787
      targetPort: 8787
  selector:
    io.kompose.service: dask-cuda-worker
status:
  loadBalancer: {}