apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mount
spec:
{{- if eq .Values.multiNode true  }}
  accessModes:
    - ReadWriteMany
  storageClassName: datamount-longhorn-{{ .Release.Namespace }}
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-sc-{{ .Release.Namespace }}
{{- end }}  
  resources:
    requests: 
      storage: 64Gi
status: {}
