apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mount
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: datamount-longhorn
  resources:
    requests:
      storage: 64Gi
status: {}
