{{- if eq .Values.multiNode false  }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    #storageclass.kubernetes.io/is-default-class: "true"
  name: gp2-retain
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}

