apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: forge-etl-python
  name: forge-etl-python
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forge-etl-python
  strategy:
{{ if eq .Values.rollingUpdate true }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "0%"
{{ else }}
    type: Recreate
{{- end }}
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: forge-etl-python
    spec:
      containers:
        - env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphistry}}:{{.Values.forgeetlpython.repository}}-{{.Values.tag}}-{{.Values.cuda.version}}
          imagePullPolicy: {{.Values.imagePullPolicy }}    
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -f http://localhost:8080/cudfhealth && curl -f http://localhost:8080/blazinghealth"
            failureThreshold: 3
            initialDelaySeconds: 180
            periodSeconds: 120
            timeoutSeconds: 30
          name: forge-etl-python
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /opt/graphistry/data
              name: data-mount
            - mountPath: /opt/graphistry/data/uploads
              name: uploads-files
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: data-mount
        - name: uploads-files
          persistentVolumeClaim:
            claimName: uploads-files
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }} 
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
status: {}

---
#service for nginx
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: forge-etl-python
  name: forge-etl-python
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: forge-etl-python
status:
  loadBalancer: {}

---

