apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: ingress-nginx
  name: nginx-configuration
  namespace: {{ .Values.ingressNamespace }}
data:
  use-forwarded-headers: "true"
  