
{{ if eq .Values.devMode false }} 

{{ if eq .Values.graphAppKitPublic true }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gak-public
  name: gak-public
spec:
{{- if eq .Values.multiNode true  }}
  accessModes:
    - ReadWriteMany
  storageClassName: datamount-longhorn
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-retain
  resources:
    requests:
      storage: 1Gi
status: {}
{{- end }}

{{- end }}

{{ if eq .Values.graphAppKitPrivate true }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gak-private
  name: gak-private
spec:
{{- if eq .Values.multiNode true  }}
  accessModes:
    - ReadWriteMany
  storageClassName: datamount-longhorn
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-retain
  resources:
    requests:
      storage: 1Gi
status: {}
{{- end }}

{{- end }}

{{- end }}