{{ if eq .Values.graphAppKitPublic true }}

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: graph-app-kit-public
  name: graph-app-kit-public
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graph-app-kit-public
  strategy:
{{ if eq .Values.rollingUpdate true }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: "0%"
{{ else }}
    type: Recreate
{{- end }}
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: graph-app-kit-public
    spec:
      initContainers:
      - name: "{{ .Chart.Name }}-init"
        image: "groundnuty/k8s-wait-for:latest"
        imagePullPolicy: {{.Values.imagePullPolicy }} 
        args: 
        - "job"
        - "nexus-migration-job-{{ .Release.Revision}}"
      - name: graph-app-kit-init
        image: acrgraphistryk8s.azurecr.io/graphistry/graph-app-kit-st:development
        command: ["/bin/sh","-c"]
        args: ["cp -r /apps/views /opt/public/views && cp -r /apps/css /opt/public/css && cp -r /apps/util /opt/public/util {{ if eq .Values.graphAppKitPrivate true }} && cp -r /apps/views /opt/private/views && cp -r /apps/css /opt/private/css && cp -r /apps/util /opt/private/util {{- end }}"]
        volumeMounts:
        - name: gak-public
          mountPath: /opt/public/
        - name: gak-private
          mountPath: /opt/private/        

      containers:
        - env:
   {{- range .Values.stENVPublic }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: acrgraphistryk8s.azurecr.io/graphistry/graph-app-kit-st:development
          #image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphAppKit.repository}}:{{.Values.graphAppKit.tag}}
          imagePullPolicy: {{.Values.imagePullPolicy }}
          livenessProbe:
            exec:
              command:
                - sh 
                - -c 
                - 'curl -Lf http://localhost:8501/dashboard/healthz'

          name: graph-app-kit-public
          ports:
            - containerPort: 8501
          resources: {}
          volumeMounts:
            - mountPath: /apps/css
              subPath: css
              name: gak-public
            - mountPath: /apps/util
              subPath: util
              name: gak-public
            - mountPath: /apps/views
              subPath: views
              name: gak-public
{{ if eq .Values.graphAppKitPrivate true }}
#graph-app-kit-private
        - env:
   {{- range .Values.stENVPrivate }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: acrgraphistryk8s.azurecr.io/graphistry/graph-app-kit-st:development
          #image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphAppKit.repository}}:{{.Values.graphAppKit.tag}}
          imagePullPolicy: {{.Values.imagePullPolicy }}
          livenessProbe:
            exec:
              command:
                - sh 
                - -c 
                - 'curl -Lf http://localhost:8502/dashboard/healthz'

          name: graph-app-kit-private
          ports:
            - containerPort: 8502
          resources: {}
          volumeMounts:
            - mountPath: /apps/css
              subPath: css
              name: gak-private
            - mountPath: /apps/util
              subPath: util
              name: gak-private
            - mountPath: /apps/views
              subPath: views
              name: gak-private
{{- end }}           
####
      restartPolicy: {{ .Values.restartPolicy }}
      serviceAccountName: job-robot
      volumes:
        - name: gak-public
          persistentVolumeClaim:
            claimName: gak-public
        - name: gak-private
          persistentVolumeClaim:
            claimName: gak-private
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}    
{{ if eq .Values.multiNode false }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }} 
status: {}


---
#service
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: graph-app-kit-public
  name: graph-app-kit-public
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: graph-app-kit-public
{{- end }}
---
#service
{{ if eq .Values.graphAppKitPrivate true }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: graph-app-kit-private
  name: graph-app-kit-private
spec:
  ports:
    - name: "8502"
      port: 8502
      targetPort: 8502
  selector:
    io.kompose.service: graph-app-kit-public
{{- end }}
