{{- if eq .Values.longhornDashboard true  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "sessionid"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
{{- if eq .Values.tls true  }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    ingress.kubernetes.io/ssl-redirect: "true"
{{- end  }}
{{- if .Values.ingress.management.annotations }}
{{ toYaml .Values.ingress.management.annotations | indent 4 }}
{{- end }}
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  rules:
    - host: longhorn.{{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
{{- if eq .Values.tls true  }}
  tls:
  - hosts: 
    - longhorn.{{ .Values.domain }}
    secretName: letsencrypt-tls
{{- end }}
{{- end }}

