apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-migration-job-{{ .Release.Revision }}
  labels:
    io.kompose.service: nexus-migration-job
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        io.kompose.service: nexus-migration-job
    spec:
      containers:
      - name: nexus-migration-job
     {{ if eq .Values.devMode false }}
        image: {{.Values.containerregistry.name}}/{{.Values.graphistry}}:{{.Values.nexus.repository}}-{{.Values.tag}}-{{.Values.cuda.version}}
      {{ else }}  
        image: graphistry/{{.Values.nexusDev.repository}}:{{.Values.tag}}-universal-dev
        
    {{ end }}         
        imagePullPolicy: {{.Values.imagePullPolicy }}    
        args: ["python", "manage.py" , "migrate"]

        env:
   {{- range .Values.env }}
            - name: {{ .name  }}
              value: {{ .value | quote }}
   {{- end }}
      restartPolicy: Never
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}