apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if .Values.ingress.management.annotations }}
  annotations:
{{ toYaml .Values.ingress.management.annotations | indent 4 }}
{{- end }}
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: caddy
                port:
                  number: 80
            path: /
            pathType: Prefix
status:
  loadBalancer: {}