apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: streamgl-viz
  name: streamgl-viz
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamgl-viz
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: streamgl-viz
    spec:
      containers:
        - env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphistry}}:{{.Values.streamglviz.repository}}-{{.Values.tag}}-{{.Values.cuda.version}}
          imagePullPolicy: {{.Values.imagePullPolicy }}   
          livenessProbe:
            exec:
              command:
                - curl
                - -Lf
                - http://localhost:8080/health
            failureThreshold: 3
            initialDelaySeconds: 180
            periodSeconds: 120
            timeoutSeconds: 30
          name: streamgl-viz
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: {{ .Values.restartPolicy }}
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }} 
status: {}


---
#service
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: streamgl-viz
  name: streamgl-viz
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: streamgl-viz
status:
  loadBalancer: {}
