apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: streamgl-vgraph-etl
  name: streamgl-vgraph-etl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamgl-vgraph-etl
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: streamgl-vgraph-etl
    spec:
      containers:
        - env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: {{.Values.azurecontainerregistry.name}}/{{.Values.graphistry}}:{{.Values.streamglvgraph.repository}}-{{.Values.tag}}-{{.Values.cuda.version}}
          imagePullPolicy: {{.Values.imagePullPolicy }}   
          livenessProbe:
            exec:
              command:
                - curl
                - -Lf
                - http://localhost:8080/health
            failureThreshold: 3
            initialDelaySeconds: 180
            periodSeconds: 120
            timeoutSeconds: 30
          name: streamgl-vgraph-etl
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /opt/graphistry/data
              name: streamgl-vgraph-etl-claim0
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: streamgl-vgraph-etl-claim0
          persistentVolumeClaim:
            claimName: streamgl-vgraph-etl-claim0
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}  
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }} 
status: {}

---
#service
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: streamgl-vgraph-etl
  name: streamgl-vgraph-etl
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: streamgl-vgraph-etl
status:
  loadBalancer: {}



#volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: streamgl-vgraph-etl-claim0
  name: streamgl-vgraph-etl-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
