apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: uploads-files
  name: uploads-files
spec:
{{- if eq .Values.multiNode true  }}
  accessModes:
    - ReadWriteMany
  storageClassName: datamount-longhorn-{{ .Release.Namespace }}
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: uploadfiles-sc-{{ .Release.Namespace }}
  resources:
    requests:
      storage: 40Gi
status: {}
{{- end }}