apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dask-operator-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dask-operator
  project: operators
  source:
    path: charts/dask-kubernetes-operator
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: nightly #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        - values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

##helm template charts/argo-cd/apps/ | kubectl apply -f -