- repo: https://github.com/rapidsai/frigate
  rev: v0.4.0 #  pre-commit autoupdate  - to keep the version up to date
  hooks:
    - id: frigate
      args:
        - --output=docs/graphistry-helm-docs.rst
        - --format=rst
        - --no-credits
        - --no-deps
