apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: argo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/graphistry/argo-helm.git
    targetRevision: HEAD #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        - ./argo-values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

##helm template charts/argo-cd/apps/ | kubectl apply -f -

#helm upgrade -i argo ./charts/argo-cd  --namespace argo --create-namespace
