apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphistry-deploy-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: graphistry
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: graphistry
  project: default
  source:
    path: cd/argo-apps/templates/graphistry-cd-templates
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: HEAD #BRANCH OR HEAD WHEN IN MAIN
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

##helm template cd/argo-apps/ | kubectl apply -f -