apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose --file ./compose/release.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
          image: graphistry/streamgl-nginx:v2.38.10-universal ##{{.Values.azurecontainerregistry.name}}/{{.Values.nginx.repository}}:{{.Values.tag}}-universal
          livenessProbe:
            exec:
              command:
                - curl 
                - -f 
                - http://localhost/healthz
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 30
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /opt/graphistry/apps/core/viz/build
              name: viz-static-files
            - mountPath: /opt/graphistry/apps/core/pivot/www
              name: pivot-static-files
            - mountPath: /opt/graphistry/apps/core/nexus/staticfiles
              name: local-media-mount
            - mountPath: /opt/graphistry/data/uploads
              name: uploads-files
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: viz-static-files
          persistentVolumeClaim:
            claimName: viz-static-files
        - name: pivot-static-files
          persistentVolumeClaim:
            claimName: pivot-static-files
        - name: local-media-mount
          persistentVolumeClaim:
            claimName: local-media-mount
        - name: uploads-files
          persistentVolumeClaim:
            claimName: uploads-files
status: {}

---
#service
apiVersion: v1
kind: Service
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose --file ./compose/release.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
