name: Graphistry-Helm-Chart
version: 0.3.5
apiVersion: v1
description: >
 Helm Charts to deploy Graphistry to kubernetes for 100x visualizations

long_description: | 

  These charts will deploy the base apps and resources for Graphistry

  .. tabs::

    .. tab:: From source
      .. code-block:: shell-session            
                
         git clone https://github.com/graphistry/graphistry-helm && cd graphistry-helm
         helm upgrade -i graphistry-resources ./charts/graphistry-helm-resources --namespace graphistry --create-namespace 
         helm upgrade -i g-chart ./charts/graphistry-helm --namespace graphistry --create-namespace 

    .. tab:: From Helm Repo
      .. code-block:: shell-session            
                
         helm repo add graphistry-helm https://graphistry.github.io/graphistry-helm/
         helm upgrade -i graphistry-resources graphistry-helm/graphistry-resources --namespace graphistry --create-namespace         
         helm upgrade -i g-chart graphistry-helm/Graphistry-Helm-Chart --namespace graphistry --create-namespace 




keywords:
  - Graphistry
  - Helm Charts
  - 100x
  - visualizations
  - kubernetes





#dependencies:
#  - name: graphistry-helm-resources
#    version: "0.3.5"
#    repository: "file://../graphistry-helm-resources"
#  - name: dask-kubernetes-operator
#    version: "2022.7.0"
#    repository: https://helm.dask.org
#  - name: kube-prometheus-stack
#    version: "40.0.*"
#    repository: https://prometheus-community.github.io/helm-charts
#  - name: dcgm-exporter
#    version: "40.0.*"
#    repository: https://nvidia.github.io/dcgm-exporter/helm-charts
#  - name: pgo
#    version: "0.6.0"
#    repository: file://../postgres-operator
#  - name: postgres-cluster
#    version: "0.6.0"
#    repository: file://../postgres-cluster
#  - name: k8s-dashboard
#    version: "2.6.1"
#    repository: file://../k8s-dashboard
#  - name: ingress-nginx
#    version: "4.2.5"
#    repository: file://../ingress-nginx
#  - name: cert-manager
#    version: "v1.9.1"
#    repository: file://../cert-manager

#footnotes: | 
