name: Graphistry-Helm-Chart
description: Helm Charts to deploy Graphistry to kubernetes for 100x visualizations
version: 0.1.6
apiVersion: v1
keywords:
  - Graphistry
  - Helm Charts
  - 100x
  - visualizations
  - kubernetes
  
