name: graphistry-helm-chart
description: Helm Charts to deploy Graphistry to kubernetes for 100x visualizations
version: 0.2.2
apiVersion: v1
keywords:
  - Graphistry
  - Helm Charts
  - 100x
  - visualizations
  - kubernetes
  
