{{- if eq .Values.global.multiNode false  }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    #storageclass.kubernetes.io/is-default-class: "true"
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: retain-sc
{{- if .Values.graphistryResources.storageClassParameters }}
parameters:
{{ toYaml .Values.graphistryResources.storageClassParameters | indent 2 }}
{{- end }}
provisioner: {{ .Values.global.provisioner }}
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}

