# longhorn storageclass setting reclaim policy to retain
{{- if eq .Values.global.multiNode true  }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-longhorn
  annotations:
    # make this class the default storage class
    #storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
{{- end }}
