apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphistry-resources-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: graphistry
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: graphistry
  project: default
  source:
    path: charts/graphistry-helm-resources
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: HEAD #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        - ../values-overrides/internal/eks-dev-values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

##helm template charts/argo-cd/apps/ | kubectl apply -f -
