apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphistry-app-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: graphistry
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: graphistry
  project: default
  source:
    path: charts/graphistry-helm
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: dev/opentelemetry #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        # - ../values-overrides/internal/eks-dev-values.yaml # resolved against source.repoURL and source.path
        - ../values-overrides/examples/k3s_example_values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


##helm template cd/argo-apps/ | kubectl apply -f -