apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: local-media-mount
  name: local-media-mount
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
{{- if eq .Values.global.multiNode true  }}
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io

{{ else }}
    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.global.provisioner }}
    volume.kubernetes.io/storage-provisioner: {{ .Values.global.provisioner }}
{{- end }}
  finalizers:
  - kubernetes.io/pvc-protection
spec:
{{- if eq .Values.global.multiNode true  }}
  accessModes:
    - ReadWriteMany
  storageClassName: datamount-longhorn-{{ .Release.Namespace }}
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-sc-{{ .Release.Namespace }}
{{- end }}
  volumeName: pvc-89de61bf-2d96-4613-9a24-fb19a93d2c43
  resources:
    requests:
      storage: 4Gi
status: {}
