version: "3.5"

networks:
  grph_net:
    name: grph_net

services:

  helm-docker:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws:ro
      - ~/.kube/config:/root/.kube/dev-cluster:ro
    command: helm install g-chart graphistry-helm/Graphistry-Helm-Chart  --set tag=$APP_TAG --set domain=eks-skinny.grph.xyz --namespace graphistry  --set tls=false --set devMode=true  --create-namespace  --dry-run
    environment:
      - APP_TAG=${APP_TAG}

  cluster-setup:
    image: helm-docker
    command: bash ./setup_deploy.sh
    environment:
      - MULTINODE=${MULTINODE}
      - TLS=${TLS}
      - APP_TAG=${APP_TAG}

  make-cluster-secrets:
    image: helm-docker
    command: bash -c "if [[ ! -z $(kubectl get secrets -n graphistry  | grep "acr-secret") ]]; then 
              echo "secret exist" && exit 0; 
            else  ./make_secret.sh; fi"
    environment:
      - SERVICE_PRINCIPAL_NAME=${SERVICE_PRINCIPAL_NAME}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - ACR_NAME=${ACR_NAME}
      - AZSUBSCRIPTION=${AZSUBSCRIPTION}
      - CONTAINER_REGISTRY_NAME=${CONTAINER_REGISTRY_NAME}


  scale-to-zero:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws:ro
      - ~/.kube/config:/root/.kube/dev-cluster:ro
    command: helm delete g-chart -n graphistry 
    environment:
      - APP_TAG=${APP_TAG}