version: "3.5"

networks:
  grph_net:
    name: grph_net

services:

  helm-docker:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws:ro
      - ~/.kube/config:/root/.kube/dev-cluster:ro
    command: helm upgrade -i g-chart graphistry-helm/Graphistry-Helm-Chart --set tls=${{ env.TLS }} --set tlsEmail="cody@graphistry.com"  --set tag=${{ env.APP_TAG }} --set domain=eks-skinny.grph.xyz --namespace graphistry  --set devMode=true --set nodeEnv=development --set appEnvironment=development --set djangoSettingsModule=config.settings.dev --set djangoDebug=True --set graphistryCPUMode=1 --set graphistryKey =${{ env.GRAPHISTRY_KEY }} --set imagePullSecrets=dockerhub-secret --create-namespace  --dry-run
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}

  cluster-setup:
    image: helm-docker
    command: bash ./setup_deploy.sh
    environment:
      - MULTINODE=${MULTINODE}
      - TLS=${TLS}
      - APP_TAG=${APP_TAG}


  make-cluster-secrets:
    image: helm-docker
    command: bash ./check-secret.sh
    environment:
      - CONTAINER_REGISTRY_NAME=${CONTAINER_REGISTRY_NAME}
      - DOCKER_USER_NAME=${DOCKER_USER_NAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_EMAIL=${DOCKER_EMAIL}



  scale-to-zero:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws:ro
      - ~/.kube/config:/root/.kube/dev-cluster:ro
    command: helm delete g-chart -n graphistry 
    environment:
      - APP_TAG=${APP_TAG}