version: "3.5"

networks:
  grph_net:
    name: grph_net

services:

  helm-docker:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws:ro
      - ~/.kube/config:/root/.kube/dev-cluster:ro
    command: helm install g-chart graphistry-helm/Graphistry-Helm-Chart  --set tag=v2.39.12 --set domain=eks-skinny.grph.xyz --namespace graphistry  --set tls=false --set devMode=true  --create-namespace  --dry-run
  
  cluster-setup:
    image: helm-docker
    command: bash ./setup_deploy.sh

  make-cluster-secrets:
    image: helm-docker
    command: bash ./make_secret.sh