version: "3.5"

services:
  helm-docker:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
    command: helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/eks-dev-values.yaml --set multiNode=${MULTINODE} --set tls=${TLS}  --set tag=${APP_TAG} --namespace graphistry   --create-namespace   
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}
      - MULTINODE=${MULTINODE}

  helm-docker-dev:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
    command: helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/skinny-values.yaml --set multiNode=${MULTINODE} --set tls=${TLS}  --set tag=${APP_TAG}  --namespace graphistry   --create-namespace  
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}
      - MULTINODE=${MULTINODE}

  cluster-setup:
    image: helm-docker
    command: bash ./setup_deploy.sh
    volumes:
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
    environment:
      - MULTINODE=${MULTINODE}
      - TLS=${TLS}
      - APP_TAG=${APP_TAG}


  aws-setup:
    image: helm-docker
    command: bash ./copy-aws-creds.sh
    volumes:
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      - SOURCE_PROFILE=${SOURCE_PROFILE}
      - CLUSTER_NAME=${CLUSTER_NAME}

  make-cluster-secrets:
    image: helm-docker
    command: bash ./make_secret.sh
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
    environment:
      - CONTAINER_REGISTRY_NAME=${CONTAINER_REGISTRY_NAME}
      - DOCKER_USER_NAME=${DOCKER_USER_NAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_USER_NAME_PROD=${DOCKER_USER_NAME_PROD}
      - DOCKER_PASSWORD_PROD=${DOCKER_PASSWORD_PROD}
      - CLUSTER_NAME=${CLUSTER_NAME}

  scale-to-zero:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
    command: helm delete g-chart -n graphistry 

