version: "3.5"


services:
  helm-docker:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube/:/root/.kube
    command: bash ./check-secret.sh && helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/eks-dev2-values.yaml  --set tag=${APP_TAG} --namespace graphistry   --create-namespace  --dry-run
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}


  helm-docker-dev:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube/:/root/.kube
    command: bash ./check-secret.sh && helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/skinny-values.yaml  --set tag=${APP_TAG}  --namespace graphistry   --create-namespace  --dry-run
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}


  cluster-setup:
    image: helm-docker
    command: bash ./setup_deploy.sh
    volumes:
      - ~/.aws:/root/.aws
      - ~/.kube/:/root/.kube
    environment:
      - MULTINODE=${MULTINODE}
      - TLS=${TLS}
      - APP_TAG=${APP_TAG}


  aws-setup:
    image: helm-docker
    command: bash ./copy-aws-creds.sh
    volumes:
      - ~/.aws:/root/.aws
      - ~/.kube/:/root/.kube
    environment:
      - MULTINODE=${MULTINODE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      - SOURCE_PROFILE=${SOURCE_PROFILE}


##not in use currently
  make-cluster-secrets:
    image: helm-docker
    command: bash ./check-secret.sh
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube/:/root/.kube
    environment:
      - CONTAINER_REGISTRY_NAME=${CONTAINER_REGISTRY_NAME}
      - DOCKER_USER_NAME=${DOCKER_USER_NAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_USER_NAME_PROD=${DOCKER_USER_NAME_PROD}
      - DOCKER_PASSWORD_PROD=${DOCKER_PASSWORD_PROD}



  scale-to-zero:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws
      - ~/.kube/:/root/.kube
    command: helm delete g-chart -n graphistry 
    environment:
      - APP_TAG=${APP_TAG}
