version: "3.5"


services:
  helm-docker:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      #- ${AWS_CREDS}:/root/.aws:ro
      #- ${KUBECONFIG}:/root/.kube/dev-cluster:ro
    command: helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/eks-dev2-values.yaml  --set tag=${APP_TAG} --namespace graphistry   --create-namespace  --dry-run
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}
      #- AWS_CREDS=${AWS_CREDS}
      #- KUBECONFIG=${KUBECONFIG}

  helm-docker-dev:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      #- ${AWS_CREDS}:/root/.aws:ro
      #- ${KUBECONFIG}:/root/.kube/dev-cluster:ro
    command: helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/skinny-values.yaml  --set tag=${APP_TAG}  --namespace graphistry   --create-namespace  --dry-run
    environment:
      - APP_TAG=${APP_TAG}
      - TLS=${TLS}
      #- AWS_CREDS=${AWS_CREDS}
      #- KUBECONFIG=${KUBECONFIG}

  cluster-setup:
    image: helm-docker
    command: bash ./setup_deploy.sh
    environment:
      - MULTINODE=${MULTINODE}
      - TLS=${TLS}
      - APP_TAG=${APP_TAG}

  aws-setup:
    image: helm-docker
    command: bash ./copy-aws-creds.sh
    environment:
      - MULTINODE=${MULTINODE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}

  make-cluster-secrets:
    image: helm-docker
    command: bash ./check-secret.sh
    environment:
      - CONTAINER_REGISTRY_NAME=${CONTAINER_REGISTRY_NAME}
      - DOCKER_USER_NAME=${DOCKER_USER_NAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_USER_NAME_PROD=${DOCKER_USER_NAME_PROD}
      - DOCKER_PASSWORD_PROD=${DOCKER_PASSWORD_PROD}



  scale-to-zero:
    build:
      context: ./scripts
      dockerfile: ../docker/Dockerfile
    image: helm-docker
    volumes:
      - ../charts/:/charts
      - ~/.aws:/root/.aws:ro
      - ~/.kube/config:/root/.kube/dev-cluster:ro
    command: helm delete g-chart -n graphistry 
    environment:
      - APP_TAG=${APP_TAG}