grafana:
  grafana.ini:
      server:
        domain: "eks-dev.grph.xyz"
        root_url: "https://eks-dev.grph.xyz/grafana"
        serve_from_sub_path: true
      auth.anonymous:
        enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
