# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

{{- if .Values.serviceAccount.create }}
{{ if not (lookup "v1" "ServiceAccount" .Release.Namespace (include "morpheus-ai-engine.serviceAccountName" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
 labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: morpheus
 name: {{ template "morpheus-ai-engine.serviceAccountName" . }}
 namespace: {{ .Release.Namespace }}
{{ end }}
{{- end }}
