{{ if eq .Values.httpTesting true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  labels:
    io.kompose.service: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: netshoot
  template:
    metadata:
      labels:
        io.kompose.network/grph: "true"
        io.kompose.service: netshoot
    spec:
      containers:
      - name: netshoot
        {{- if eq .Values.global.containerregistry.name "docker.io" }}
        image: nicolaka/netshoot:latest
        {{- else }}
        image: {{.Values.global.containerregistry.name}}/nicolaka/netshoot:latest
        {{- end }}        
        command: ["/bin/bash"]
        args: ["-c", "while true; do ping localhost; sleep 60;done"]
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
{{ end }}


