{{ if .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: grph
spec:
{{ if eq .Values.networkPolicy.strict true }} 
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/grph: "true"
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
{{ else }} 
  ingress:
  - {}
  egress:
  - {}
{{ end }}
  podSelector:
    matchLabels:
      io.kompose.network/grph: "true"

{{ end }}