apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: v0.3.5 #BRANCH OR HEAD WHEN IN MAIN
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true