apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphistry-deploy-ci
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: graphistry
  project: default
  source:
    path: charts/argo-cd/apps/templates/graphistry-ci-templates
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: v0.3.5
    helm:
      valueFiles:
        - ../graphistry-helm/overrides/internal/eks-dev-values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true