{{if eq .Values.metrics true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
data:
  config.hcl: |
    listen {
      port = 4040
    }

    namespace "nginx" {
      source = {
        syslog {
          listen_address = "udp://127.0.0.1:5531"
          format = "auto"
          tags = [
            "nginx"
          ]
        }
      }
      relabel "request_uri" {
        from = "request"
        split = 2
        separator = " "  
      }
    

      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\"rt=$request_time uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\""

      labels {
        app = "default"
        service = "nginx"
        environment =  {{.Release.Namespace | quote }}
        hostname = "https://{{ .Values.domain }}"
      }
      histogram_buckets = [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
    }

{{- end }}