# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: mlflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
    spec:
      {{- if .Values.mlflow.withEngine }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - ai-engine
          topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        args: [ "/bin/sh", "-c", "mlflow server -h 0.0.0.0 --backend-store-uri sqlite:////tmp/mlflow-db.sqlite --default-artifact-root /mlflow/artifacts --static-prefix /morpheus/mlflow" ]
        env:
        - name: TRITON_MODEL_REPO
          value: /common/triton-model-repo
        - name: TRITON_URL
          # no scheme
          value: ai-engine:8000
        image: "{{ .Values.mlflow.registry }}/{{ .Values.mlflow.image }}:{{ .Values.mlflow.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- if .Values.platform.openshift }}
        securityContext:
          privileged: true
        {{- end }}
        volumeMounts:
        - mountPath: /common/models
          name: model-path
        - mountPath: /mlflow/artifacts
          name: mlflow-path
        - mountPath: /common/triton-model-repo
          name: triton-model-path
      serviceAccountName: {{ template "morpheus-mlflow.serviceAccountName" . }}
      volumes:
      - name: model-path
        hostPath:
          path: {{ .Values.hostCommonPath }}/models
          type: DirectoryOrCreate
      - name: mlflow-path
        hostPath:
          path: {{ .Values.hostCommonPath }}/mlflow/artifacts
          type: DirectoryOrCreate
      - name: triton-model-path
        hostPath:
          path: {{ .Values.hostCommonPath }}/triton-model-repo
          type: DirectoryOrCreate
