# Default values for morpheus-mlflow
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ngc:
  username: "$oauthtoken"
  apiKey: ""
  org: ""
  team: ""

mlflow:
  registry: "nvcr.io/nvidia/morpheus"
  image: mlflow-triton-plugin
  version: 1.28.0
  # make the MLflow deployment Pending of
  # where the AI Engine is scheduled
  withEngine: false

dashboardPort: 30500
hostCommonPath: /opt/morpheus/common

# use 'Always' for development
imagePullPolicy: IfNotPresent
 
imagePullSecrets:
- name: nvidia-registrykey-secret
# for Fleet Command deployments
# - name: imagepullsecret

# we need privileged pods to
# use certain hostPaths on OpenShift
serviceAccount:
  create: false
  name: morpheus

platform:
  openshift: false

# deploy a LB (AWS) instead
# of a NodePort
loadBalancer:
  enabled: false
