domain: eks-dev.grph.xyz 
tlsEmail: "cody@graphistry.com" 
tls: true
metrics: false
fwdHeaders: true
volumeName:
  dataMount: pvc-7e69c7eb-79b0-4e0b-b23e-0c06f8e79b4f
  localMediaMount: pvc-e11b1eeb-3d13-44d8-83c5-65e52ae42a8d
  gakPublic: pvc-838682e3-f807-4fce-a584-d30cb2a2f104
  gakPrivate: pvc-cee28c9f-87dd-4e9c-91ec-0a38213ece91
networkPolicy:
  strict: true

graphistryResources:
  storageClassParameters:
      csi.storage.k8s.io/fstype: ext4
      type: gp2

  ## createServiceAccount: true only true on initial deployment
k8sDashboard:
  enabled: true
  readonly: false
  createServiceAccount: false

#example values.yaml of an aws eks based deployment

grafana:
  grafana.ini:
      server:
        domain: "eks-dev.grph.xyz"
        root_url: "https://eks-dev.grph.xyz/grafana"
        serve_from_sub_path: true
      auth.anonymous:
        enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

ingress-nginx:
  controller:
    metrics:
      enabled: true 
      serviceMonitor:
        enabled: true 
        additionalLabels:
          release: "prometheus"


cert-manager: #defined by either the name or alias of your dependency in Chart.yaml
  namespace: cert-manager
  installCRDs: true
  createCustomResource: true
      
global:
  provisioner: ebs.csi.aws.com
  tag: v2.39.30
  nodeSelector: {"accelerator": "nvidia"}
  #change log levels
  #logs:
  #  LogLevel: "TRACE"
  #  GraphistryLogLevel: "TRACE"
  #multinode setting
  #multiNode: true
  imagePullPolicy: Always
  imagePullSecrets: 
    - name: docker-secret-prod
  postgresVolumeLabel: graphistry-postgres
  #dev mode for debugging with nexus, postgres and nginx
  #devMode: true




#helm upgrade -i prometheus-community ./charts/kube-prometheus-stack --values ./charts/values-overrides/internal/eks-dev-values.yaml --namespace prometheus --create-namespace --dry-run
#helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/values-overrides/internal/eks-dev-values.yaml --namespace graphistry --create-namespace --dry-run 
