domain: eks-skinny.grph.xyz   
tls: true
tlsEmail: "cody@graphistry.com" 
nodeEnv: development 
appEnvironment: development 
djangoSettingsModule: "config.settings.dev" 
graphistryCPUMode: "1" 
djangoDebug: "True"
httpTesting: true

#volume pv names go here after initial deployment and provisioning
volumeName:
  dataMount: 
  localMediaMount: 
  gakPublic: 
  gakPrivate: 


#example values.yaml of an aws eks based deployment



graphistryResources:
  storageClassParameters:
      csi.storage.k8s.io/fstype: ext4
      type: gp2


      
global:
  provisioner: ebs.csi.aws.com
  imagePullPolicy: Always
  imagePullSecrets: 
    - name: dockerhub-secret
  logs:
    LogLevel: INFO
    GraphistryLogLevel: INFO
  tag: v2.39.28-admin
  devMode: true 
#helm upgrade -i g-chart ./charts/graphistry-helm --values ./charts/graphistry-helm/skinny-values.yaml --set tag=v2.39.17-koa-sso-new  --namespace graphistry --create-namespace