apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stacks-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: prometheus-community
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    path: charts/kube-prometheus-stack
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: nightly #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        - ../values-overrides/internal/eks-dev-values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


##helm template charts/argo-cd/apps/ | kubectl apply -f -