apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-cd
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  project: default
  source:
    path: charts/postgres-operator
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: v0.3.5 #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        - values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

##helm template charts/argo-cd/apps/ | kubectl apply -f -