apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dask-operator-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: operators
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dask-operator
  project: default
  source:
    path: cd/repo
    repoURL: https://github.com/graphistry/graphistry-helm.git
    targetRevision: HEAD #BRANCH OR HEAD WHEN IN MAIN
#    helm:
#      valueFiles:
#        - values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

##helm template cd/argo-apps | kubectl apply -f -