apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: operators
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  project: default
  source:
    path: helm/install
    repoURL: https://github.com/CrunchyData/postgres-operator-examples.git
    targetRevision: HEAD #terraform #BRANCH OR HEAD WHEN IN MAIN
    helm:
      valueFiles:
        - values.yaml # resolved against source.repoURL and source.path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

##helm template charts/argo-cd/apps/ | kubectl apply -f -