apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.4.3
    repository: https://argoproj.github.io/argo-helm


# helm upgrade -i argo-cd ./charts/argo-cd --namespace argo-cd --create-namespace