#example values.yaml for a azure aks deployment with a private repository
ingressNamespace: default
#volume pv names go here after initial deployment and provisioning
volumeName:
  dataMount: 
  localMediaMount: 
  gakPublic: 
  gakPrivate: 



graphistryResources:
    storageClassParameters:
        skuName: StandardSSD_LRS  


  ## createServiceAccount: true only true on initial deployment
k8sDashboard:
  enabled: true
  readonly: false
  createServiceAccount: false

#example values.yaml of an aws eks based deployment


grafana:
  grafana.ini:
      server:
        domain: eks-dev.grph.xyz
        root_url: https://eks-dev.grph.xyz/k8s/grafana
        serve_from_sub_path: true
      auth.anonymous:
        enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false


ingress-nginx:
  controller:
    metrics:
      enabled: true 
      serviceMonitor:
        enabled: true 
        additionalLabels:
          release: "prometheus"


cert-manager: #defined by either the name or alias of your dependency in Chart.yaml
  namespace: cert-manager
  installCRDs: true
  createCustomResource: true

global:
  provisioner: disk.csi.azure.com
  containerregistry:
    name: 
  imagePullSecrets: 
    - name: dockerhub-secret