#example values.yaml for a azure aks deployment with a private repository
graphAppKitusername:
graphAppKitpassword:
ingressNamespace: default


graphistry-helm-resources:
    storageClassParameters:
        skuName: StandardSSD_LRS  

global:
  provisioner: disk.csi.azure.com
  containerregistry:
    name: 
  imagePullSecrets: 