apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: graphistry-otel-collector
spec:
  config: |
    receivers:
    otlp:
        protocols:
        grpc:

    exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
        system: graphistry

    logging:
        loglevel: warn

    # jaeger:
    #   endpoint: "jaeger:14250" # jaeger collector grpc endpoint
    #   tls:
    #     insecure: true

    processors:
    batch:

    memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30

    extensions:
    health_check:
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679

    service:
    extensions: [pprof, zpages, health_check]
    pipelines:
        metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, prometheus]