global:
   #- Each StorageClass has a provisioner that determines what volume plugin is used for provisioning PVs.
  provisioner: kubernetes.io/aws-ebs #storage class provisioner
  multiNode: false # multinode selector switch to determine if going multi/single node
  containerregistry:  #container registry name
    name: acrgraphistryk8s.azurecr.io
  devMode: false  #dev mode for debugging with nexus, postgres and nginx
  postgres:
    repository: graphistry-postgres  #postgres repository name 
    name: graphistry #postgres db name
    user: graphistry #postgres db user
    port: 5432  #port for postgres service to listen on
    host: postgres  #hostname for postgres
  tag: latest  #tag for the docker image
  #image pull policy
  imagePullPolicy: IfNotPresent ##image pull policy could also be Always
  restartPolicy: Always #restart policy
  imagePullSecrets: [] #image pull secrets name
  #  - name: docker-secret
  nodeSelector: #node selector to determine which node to deploy cluster to
  #{"accelerator": "nvidia"}
  #--set nodeSelector."accelerator"=nvidia
  #{"kubernetes.io/hostname": "ip-172-31-32-176.us-east-2.compute.internal"}
  #--set nodeSelector."kubernetes\\.io/hostname"=ip-172-31-7-234.us-east-2.compute.internal
  logs: #log levels
    LogLevel: INFO
    GraphistryLogLevel: INFO
  postgresVolumeLabel:  #postgres volume label