apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: caddyfile-configmap
  name: caddy-config
data:
  Caddyfile: |
    :80 {
          respond /caddy/health/ 200 {
                  body "{\"success\": true}"
                  close
          }
          reverse_proxy nginx:80 {
                  trusted_proxies private_ranges
          }
    }
