apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: caddyfile-configmap
  name: caddy-config
data:
  Caddyfile: |
    :80 {
       log {
         level DEBUG
       }
       @mismatchedHost {
           not host your-domain.grph.xyz localhost
       }
       handle @mismatchedHost {
           respond 400
       }
       respond /caddy/health/ 200
       handle /jaeger* {
           reverse_proxy jaeger:16686
       }
       # Route to prometheus
       handle /prometheus* {
           reverse_proxy prometheus:9090
       }
       # Routes for Grafana
       handle /grafana* {
           reverse_proxy grafana:3000
       }
       # Default reverse proxy for all other paths
       reverse_proxy nginx:80 {
           header_down Strict-Transport-Security max-age=2592000;
       }
    }