apiVersion: v2
name: cert-manager
description: A Helm chart with cert-manager as subchart
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: cert-manager
    version: v1.9.1
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled