apiVersion: v2
name: cert-manager
description: A Helm chart with cert-manager as subchart
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: cert-manager
    version: v1.9.1
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled

long_description: | 
  Install cert-manager to manage TLS certificates
  ---------------------------------------------------
    .. tabs::

      .. tab:: Local from Source
        .. code-block:: shell-session            
                  
          git clone https://github.com/graphistry/graphistry-helm && cd graphistry-helm
          cd graphistry-helm/charts/cert-manager && helm dep build
          helm upgrade -i argo-cd ./charts/cert-manager --namespace cert-manager --create-namespace 
  

      .. tab:: From Graphistry Helm Repo
        .. code-block:: shell-session            
                  
          helm repo add graphistry-helm https://graphistry.github.io/graphistry-helm/
          helm upgrade -i cert-manager graphistry-helm/cert-manager --namespace cert-manager --create-namespace
          

      .. tab:: From Cert-Manager Helm Repo
        .. code-block:: shell-session            
                  
          helm upgrade -i cert-manager cert-manager --repo https://charts.jetstack.io --namespace cert-manager --create-namespace 

  Once cert manager is deployed you can enable TLS on the values.yaml override for the graphistry helm chart by setting the following values

  .. code-block:: yaml

    domain: <domain you own> 
    tlsEmail: "<email to use for letsencrypt>" 
    tls: true