{{ if eq .Values.telemetryEnv.ENABLE_OPEN_TELEMETRY true }}
  {{ if eq .Values.telemetryEnv.OTEL_CLOUD_MODE false }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-configmap
data:
  datasource.yml: |
    {{ .Files.Get "grafana-config-files/provisioning/datasources/datasource.yml" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-configmap
data:
  dashboard.yml: |
    {{ .Files.Get "grafana-config-files/provisioning/dashboards/dashboard.yml" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dcgm-dashboard-configmap
data:
  dcgm-exporter-dashboard.json: |
    {{ .Files.Get "grafana-config-files/provisioning/dashboards/dcgm-exporter-dashboard.json" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-node-exporter-dashboard-configmap
data:
  node-exporter-dashboard.json: |
    {{ .Files.Get "grafana-config-files/provisioning/dashboards/node-exporter-dashboard.json" | indent 4 }}

  {{- end }}
  {{- end }}
