# {{- if .Values.telemetryEnv.ENABLE_PROMETHEUS }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: prometheus-ingress
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/affinity: "cookie"
#     nginx.ingress.kubernetes.io/session-cookie-name: "sessionid"
#     nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
#     nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
#     nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ProxyBodySize }}
#     {{- if .Values.tls }}
#     kubernetes.io/tls-acme: "true"
#     cert-manager.io/cluster-issuer: "letsencrypt-production-{{ .Release.Namespace }}"
#     ingress.kubernetes.io/ssl-redirect: "true"
#     {{- else if .Values.tlsStaging }}
#     kubernetes.io/tls-acme: "true"
#     cert-manager.io/cluster-issuer: "letsencrypt-staging-{{ .Release.Namespace }}"
#     ingress.kubernetes.io/ssl-redirect: "true"
#     {{- end }}
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /metrics
#             pathType: Prefix
#             backend:
#               service:
#                 name: prometheus
#                 port:
#                   number: 8889
# {{- end }}
