{{ if eq .Values.global.ENABLE_OPEN_TELEMETRY true }}
  {{ if eq .Values.telemetryEnv.OTEL_CLOUD_MODE false }}
{{- if and (eq .Values.global.ENABLE_CLUSTER_MODE true) (eq .Values.global.IS_FOLLOWER true) }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "sessionid"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ProxyBodySize }}
{{- if eq .Values.tls true  }}
  tls:
  - hosts:
    - {{.Values.domain}}
    secretName: letsencrypt-tls-{{ .Release.Namespace }}
{{- else if eq .Values.tlsStaging true }}
  tls:
  - hosts:
    - {{.Values.domain}}
    secretName: letsencrypt-staging-{{ .Release.Namespace }}
{{- end }}
{{- if .Values.ingress.management.annotations }}
{{ toYaml .Values.ingress.management.annotations | indent 4 }}
{{- end }}

spec:
  ingressClassName:  {{ .Values.global.ingressClassName | quote }}
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
{{- end }}
{{- end }}
{{- end }}
