{{ if eq .Values.global.ENABLE_OPEN_TELEMETRY true }}
  {{ if eq .Values.global.telemetryStack.OTEL_CLOUD_MODE false }}
{{- if and (eq .Values.global.ENABLE_CLUSTER_MODE true) (eq .Values.global.IS_FOLLOWER true) }}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-configmap
data:
  jaeger-ui.json: |-
    {
      "monitor": {
        "menuEnabled": true
      },
      "dependencies": {
        "menuEnabled": true
      }
    }
{{ end }}
{{ end }}
{{- end }}
