{{ if eq .Values.global.ENABLE_OPEN_TELEMETRY true }}
  {{- if eq .Values.global.telemetryStack.OTEL_CLOUD_MODE true }}
{{- if and (eq .Values.global.ENABLE_CLUSTER_MODE true) (eq .Values.global.IS_FOLLOWER true) }}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-cloud-configmap
data:
  otel-collector-config.yml: |-
    extensions:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
      health_check:
      basicauth/otlp:
        client_auth:
          username: ${env:OTEL_COLLECTOR_OTLP_USERNAME}
          password: ${env:OTEL_COLLECTOR_OTLP_PASSWORD}

    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      otlphttp:
        endpoint: ${env:OTEL_COLLECTOR_OTLP_HTTP_ENDPOINT}
        auth:
          authenticator: "basicauth/otlp"
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
        sending_queue:
          enabled: true
          num_consumers: 2
          queue_size: 5000

    processors:
      attributes/system-attribute:
        actions:
          - key: system
            value: "graphistry"
            action: insert

      filter/traces:
        error_mode: ignore
        traces:
          span:
            - IsMatch(attributes["http.route"], "/list\\?skipContextTest=.*") and attributes["http.status_code"] == 200
            - IsMatch(attributes["http.target"], "/list\\?skipContextTest=.*") and attributes["http.status_code"] == 200
            - IsMatch(attributes["http.route"], "/check-workers.*") and attributes["http.status_code"] == 200
            - IsMatch(attributes["http.target"], "/check-workers.*") and attributes["http.status_code"] == 200
            - IsMatch(attributes["http.route"], "/read.*") and attributes["http.status_code"] == 200
            - IsMatch(attributes["http.target"], "/read.*") and attributes["http.status_code"] == 200
            - IsMatch(attributes["http.route"], "/health.*") or IsMatch(attributes["http.target"], "/health.*")
            - name == "readHandler" and attributes["http.status_code"] == 200
      batch:
        send_batch_size: 2000
        timeout: 5s
        send_batch_max_size: 0
      memory_limiter:
        limit_mib: 450
        check_interval: 5s
        spike_limit_mib: 150

    service:
      extensions: [pprof, zpages, health_check, basicauth/otlp]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes/system-attribute]
          exporters: [otlphttp]

        traces:
          receivers: [otlp]
          processors: [memory_limiter, filter/traces, batch, attributes/system-attribute]
          exporters: [otlphttp]
{{- end }}
{{- end }}
{{- end }}
