{{ if eq .Values.global.ENABLE_OPEN_TELEMETRY true }}
  {{ if eq .Values.global.telemetryStack.OTEL_CLOUD_MODE false }}
{{- if and (eq .Values.global.ENABLE_CLUSTER_MODE true) (eq .Values.global.IS_FOLLOWER true) }}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-collector:8889']
          - targets: ['otel-collector:8888']
      - job_name: 'dcgm-exporter'
        scrape_interval: 1s
        static_configs:
          - targets: ['dcgm-exporter:9400']
      - job_name: 'node-exporter'
        scrape_interval: 1s
        static_configs:
          - targets: ['node-exporter:9100']
{{ end }}
{{ end }}
{{- end }}
