
name: helm setup and deployment
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: version and azure envvars
        #TODO PR_NUMBER: wat - https://github.com/actions/checkout/issues/58
        run: |
          az --version && echo "has az"
          echo "SERVICE_PRINCIPAL_NAME =${{ secrets.SERVICE_PRINCIPAL_NAME  }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
          echo "ACR_NAME=${{ secrets.ACR_NAME }}" >> $GITHUB_ENV
          echo "AZSUBSCRIPTION=${{ secrets.AZSUBSCRIPTION }}" >> $GITHUB_ENV
          echo "CONTAINER_REGISTRY_NAME=${{ secrets.CONTAINER_REGISTRY_NAME }}" >> $GITHUB_ENV
          echo "MULTINODE=${{ secrets.MULTINODE }}" >> $GITHUB_ENV
          echo "TLS=${{ secrets.TLS }}" >> $GITHUB_ENV
          echo "APP_TAG=${{ secrets.APP_TAG }}" >> $GITHUB_ENV

## docker compose build
      - name: Build the cluster
        run: docker-compose -f dev-compose/docker-compose.yml build

## docker compose deploy
      - name: setup the cluster
        run:  docker-compose -f dev-compose/docker-compose.yml  cluster-setup up 
##needs to run only once 

## docker compose deploy
      - name: create cluster secrets
        run:  docker-compose -f dev-compose/docker-compose.yml  make-cluster-secrets up 
# needs to only run once
      - name: deploy the cluster
        run: docker-compose -f dev-compose/docker-compose.yml helm-docker up