name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: get aux charts for release
        run: bash chart-bundler/bundler.sh

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: /home/runner/work/graphistry-helm/graphistry-helm/charts
          config: /home/runner/work/graphistry-helm/graphistry-helm/.github/config/chart-releaser.yaml

      - name: install yq
        run: |
          sudo snap install yq

      - name: Get Chart version
        run: |
          echo "TAG_NAME=$(cat /home/runner/work/graphistry-helm/graphistry-helm/charts/graphistry-helm/Chart.yaml | yq .version)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Bundle-Charts-Release-${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: 'Bundle-Charts-Release-${{ env.TAG_NAME }}.tgz'
