{{ if eq .Values.telemetryEnv.ENABLE_OPEN_TELEMETRY true }}
  {{ if eq .Values.telemetryEnv.OTEL_CLOUD_MODE false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "sessionid"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.parent.ProxyBodySize }}
{{- if eq .Values.parent.tls true  }}
  tls:
  - hosts:
    - {{.Values.parent.domain}}
    secretName: letsencrypt-tls-{{ .Release.Namespace }}
{{- else if eq .Values.parent.tlsStaging true }}
  tls:
  - hosts:
    - {{.Values.parent.domain}}
    secretName: letsencrypt-staging-{{ .Release.Namespace }}
{{- end }}
{{- if .Values.parent.ingress.management.annotations }}
{{ toYaml .Values.parent.ingress.management.annotations | indent 4 }}
{{- end }}

spec:
  rules:
    - http:
        paths:
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
{{- end }}
{{- end }}
